config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'visitor/index'
  #get '/projects/:id', to: 'projects#show', as: 'projects'
  resources :projects
  #get "/pages/*id" => 'pages#show', as: :page, format: false
  root to:'projects#index'
  post 'auth_user' => 'authentication#authenticate_user'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  def self.search(search)
  where("titre LIKE ? OR description LIKE ? OR environementTechnologique LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api_controller.rb
class ApiController < ApplicationController::Base
  before_filter :verify_jwt_token
  def verify_jwt_token
    head :unauthorized if request.headers['Authorization'].nil? ||
      !AuthToken.valid?(request:headers['Authorization'].split(' ').last)
  end
end

app/controllers/application_controller (copy).rb
class ApplicationController < ActionController::API
  include Response
  include ExceptionHandler
  attr_reader :current_user
  protected
  def authenticate_request!
    unless user_id_in_token?
      render json: { errors: ['Not Authenticated'] }, status: :unauthorized
      return
    end
    @current_user = User.find(auth_token[:user_id])
  rescue JWT::VerificationError, JWT::DecodeError
    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
  end
  private
  def http_token
    @http_token ||= if request.headers['Authorization'].present?
                      request.headers['Authorization'].split(' ').last
                    end
  end
  def auth_token
    @auth_token ||= JsonWebToken.decode(http_token)
  end
  def user_id_in_token?
    http_token && auth_token && auth_token[:user_id].to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :authenticate_user!
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authenticate_user
    user = User.find_for_database_authentication(email: params[:email])
    if user.valid_password?(params[:password])
      render json: payload(user)
    else
      render json: {errors: ['Invalid Username/Password']}, status: :unauthorized
    end
  end
  private
  def payload(user)
    return nil unless user and user.id
    {
        auth_token: JsonWebToken.encode({user_id: user.id}),
        user: {id: user.id, email: user.email}
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

include HighVoltage::StaticPage


before_action :authenticate_user!
#before_action :authenticate_request!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    if params[:search]
      @projects = Project.search(params[:search])
    else
      @projects = Project.all
    end
    #respond_to do |format|
      #format.html # index.html.erb
      #format.xml  { render :xml => @projects }
    #end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }

    end
  end


  # GET /projects/new
  # GET /projects/new.xml

  def new
  @project = Project.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  def project_params
    params.require(:project).permit(
      :titre, :description, :dateDebut,:dateFin,:nbHeuresSemaine,:renumeration,:environementTechnologique,:coodonneeDeLaPersonneAContacter
    )
    end
end

app/controllers/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def index
        render json: User.all
      end
    end
  end
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  def index
  end
  #before_action :authenticate_request!
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>

<% flash.each do |name, msg| %>

<% if msg.is_a?(String) %>

<div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">

<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

<%= content_tag :div, msg, :id => "flash_#{name}" %>

</div>

<% end %>

<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>

<li><%= link_to t('layouts.shared.navigation.edit_account', :default => 'Edit account'), edit_user_registration_path, :class => "nav-link" %></li>


<li><%= link_to t('layouts.shared.navigation.sign_out', :default => 'Sign out'), destroy_user_session_path, :method=>'get', :class => "nav-link" %></li>


<% else %>

<li><%= link_to t('layouts.shared.navigation.sign_in', :default => 'Sign in') , new_user_session_path, :class => "nav-link" %></li>

<li><%= link_to t('layouts.shared.navigation.sign_up', :default => 'Sign up'), new_user_registration_path, :class => "nav-link" %></li>

<% end %>

<% if user_signed_in? %>

<% if current_user.try(:admin?) %>

<li><%= link_to t('layouts.shared.navigation.users', :default => 'Users'), users_path %></li>

<% end %>

<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 beta2 %>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

<!-- Brand and toggle -->

<%= link_to 'Application de demande de stages', root_path, class: 'navbar-brand' %>


<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">

<span class="navbar-toggler-icon"></span>

</button>

<div class="collapse navbar-collapse" id="navbarCollapse">

<ul class="navbar-nav mr-auto">

<%= render 'layouts/nav_links_for_auth' %>

</ul>

<% if user_signed_in? %>
  <%= form_tag(projects_path, :method => "get", id: "search-form",class:"form-inline mt-2 mt-md-0") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Rechercher projets",class:"form-control mr-sm-2" %>
      <%= submit_tag "Search",class:"btn btn-outline-success my-2 my-sm-0", :name => nil %>
  <% end %>
<% end %>
</div>

</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', page_path('about') %></li>

<li><%= link_to 'Legal', page_path('legal') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>

      <html>

      <head>

<meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title><%= content_for?(:title) ? yield(:title) : "Mon App." %></title>

<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Mon App." %>">


<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>


<%= javascript_include_tag 'https://js.stripe.com/v2/' %>


<%= csrf_meta_tags %>


<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->

<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

<!--[if lt IE 9]>

<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>

<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

<![endif]-->


      </head>

      <body>

      <header>

<%= render 'layouts/navigation' %>

      </header>

      <main role="main" class="container">

<%= render 'layouts/messages' %>

<%= yield %>

      </main>

      </body>

      </html> 

app/views/layouts/show.html.erb
<div class="alert alert-warning">
  <p>
    A project has a name, and an owner. It has many tasks, and many people as well.
    For sake of the example, we assume people only work on one project. While owners can have many projects.
    A project can have many tags. You can link an existing tag, or add a new tag and link to that.


  </p></div>
<table class="table">
  <tr>
    <td>Name</td>
    <td>
      <%= @project.name %>
    </td>
  </tr>
  <tr>
    <td>Owned by</td>
    <td>
      <%= (@project.owner ? @project.owner.try(:name) : 'no owner yet') %>
    </td>
  </tr>
</table><h3>Tasks
</h3>
<p>
  List all the tasks here

</p>
<table class="table">
  <% @project.tasks.each do |task|
  %>
    <tr>
      <td><%= task.name %>
      </td>
      <td><%= task.description %>
      </td>
      <td><%= task.done %></td>
    </tr>
  <% end %></table><h3>People
</h3>
<table class="table">
  <% @project.people.each do |person|
  %>
    <tr>
      <td><%= person.name %>
      </td>
      <td><%= person.role %>
      </td>
      <td><%= person.description %>

      </td>
    </tr>
  <% end %></table><h3>Tags
</h3>
<table class="table">
  <% @project.tags.each do |tag|
  %>
    <tr>
      <td><%= tag.name %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> | <%= link_to 'Back', projects_path %>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<h3>Titre</h3>

<p>paragraphe 1.</p>

<p>paragraphe 2.</p>

<p>paragraphe 3.</p>

app/views/pages/legal.html.erb
<% content_for :title do %>Legal<% end %>

<h3>Legal</h3>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :titre, :label => 'Le titre du projet' %>
  <%= f.input :description, :label => 'La description du projet'%>
  <%= f.input :dateDebut, :label => 'La date de debut du projet' %>
  <%= f.input :dateFin, :label => 'La date de fin du projet' %>
  <%= f.input :nbHeuresSemaine, :label => 'Le nombre d\'heure par semaine' %>
  <%= f.input :renumeration, :label => 'Le salaire pour le projet' %>
  <%= f.input :environementTechnologique, :label => 'L\'environnement technologique' %>
  <%= f.input :coodonneeDeLaPersonneAContacter, :label => 'Les coordonnees de la personne a contacter' %>
  <div class="actions">
    <%= f.button :submit, :disable_with => 'Please wait ...' %>
  </div>
<% end %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Editing project
</h1>
<%= render 'form' %>

<%= link_to 'Show', @project %>
'|'
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% if user_signed_in? %>
<h1>Listing projects
</h1>
  <% if @projects.blank? %>
    <h4>There are no projects containing the term <%= params[:search] %>.</h4>
  <% else %>
    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
      </thead>
        <tbody>
        <% @projects.each do |project|
        %>
          <tr>
            <td><%= project.titre %>
            </td>
            <td>
              <%= link_to 'Show', project, class: 'btn btn-default btn-xs' %>
              <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, class: 'btn btn-xs btn-danger' %>
            </td>
          </tr>
  <% end %>
      </tbody>
    </table>
  <%= link_to 'Nouvelle offre', new_project_path %>
<% end %>
<% else %>
<h1>Veuillez vous connecter pour voir les offres de stages
</h1>
<% end %>

app/views/projects/new.html.erb
<% if user_signed_in? %>
<h1>New project
</h1>
<%= render 'form' %>

<%= link_to 'Back', projects_path%>
<% else %>
<h1>Veuillez vous connecter pour voir les offres de stages
</h1>
<% end %>

app/views/projects/show.html.erb
<div class="alert alert-warning">
  <p>
    Voici le projet en question.
  </p></div>
<table class="table">
  <tr>
    <td>Titre :</td>
    <td>
      <%= @project.titre %>
    </td>
  </tr>
  <tr>
    <td>Description :</td>
    <td>
      <%= @project.description %>
    </td>
  <tr>
    <td>Date debut :</td>
    <td>
      <%= @project.dateDebut %>
    </td>
  </tr>
  <tr>
    <td>Date fin :</td>
    <td>
      <%= @project.dateFin %>
    </td>
  </tr>
  <tr>
    <td>Nombre heures par semaine :</td>
    <td>
      <%= @project.nbHeuresSemaine %>
    </td>
  </tr>
  <tr>
    <td>Remuneration :</td>
    <td>
      <%= @project.renumeration %>
    </td>
  </tr>
  <tr>
    <td>Environnement Technologique :</td>
    <td>
      <%= @project.environementTechnologique %>
    </td>
  </tr>
  <tr>
    <td>Coordonnees de la personne a contacter :</td>
    <td>
      <%= @project.coodonneeDeLaPersonneAContacter %>
    </td>
  </tr>
</table>

<%= link_to 'Edit', edit_project_path(@project) %> | <%= link_to 'Back', projects_path %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/visitor/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/visitor/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/visitor/edit.html.erb
<h1>Editing project
</h1>
<%= render 'form' %>

<%= link_to 'Show', @project %>
'|'
<%= link_to 'Back', projects_path %>

app/views/visitor/index.html.erb
<h1>Bienvenue dans Visitor#index</h1>
<p>Find me in app/views/visitor/index.html.erb</p>

app/views/visitor/new.html.erb
<h1>New project
</h1>
<%= render 'form' %>

<%= link_to 'Back', projects_path%>

app/views/visitor/show.html.erb
<div class="alert alert-warning">
  <p>
    A project has a name, and an owner. It has many tasks, and many people as well.
    For sake of the example, we assume people only work on one project. While owners can have many projects.
    A project can have many tags. You can link an existing tag, or add a new tag and link to that.


  </p></div>
<table class="table">
  <tr>
    <td>Name</td>
    <td>
      <%= @project.name %>
    </td>
  </tr>
  <tr>
    <td>Owned by</td>
    <td>
      <%= (@project.owner ? @project.owner.try(:name) : 'no owner yet') %>
    </td>
  </tr>
</table><h3>Tasks
</h3>
<p>
  List all the tasks here

</p>
<table class="table">
  <% @project.tasks.each do |task|
  %>
    <tr>
      <td><%= task.name %>
      </td>
      <td><%= task.description %>
      </td>
      <td><%= task.done %></td>
    </tr>
  <% end %></table><h3>People
</h3>
<table class="table">
  <% @project.people.each do |person|
  %>
    <tr>
      <td><%= person.name %>
      </td>
      <td><%= person.role %>
      </td>
      <td><%= person.description %>

      </td>
    </tr>
  <% end %></table><h3>Tags
</h3>
<table class="table">
  <% @project.tags.each do |tag|
  %>
    <tr>
      <td><%= tag.name %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> | <%= link_to 'Back', projects_path %>

app/views/visitor/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>